# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: application.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='application.proto',
  package='PB_App',
  syntax='proto3',
  serialized_options=b'\n\037com.flipperdevices.protobuf.app',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11\x61pplication.proto\x12\x06PB_App\"*\n\x0cStartRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x02 \x01(\t\"\x13\n\x11LockStatusRequest\"$\n\x12LockStatusResponse\x12\x0e\n\x06locked\x18\x01 \x01(\x08\x42!\n\x1f\x63om.flipperdevices.protobuf.appb\x06proto3'
)




_STARTREQUEST = _descriptor.Descriptor(
  name='StartRequest',
  full_name='PB_App.StartRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='PB_App.StartRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='args', full_name='PB_App.StartRequest.args', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=71,
)


_LOCKSTATUSREQUEST = _descriptor.Descriptor(
  name='LockStatusRequest',
  full_name='PB_App.LockStatusRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=92,
)


_LOCKSTATUSRESPONSE = _descriptor.Descriptor(
  name='LockStatusResponse',
  full_name='PB_App.LockStatusResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='locked', full_name='PB_App.LockStatusResponse.locked', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=130,
)

DESCRIPTOR.message_types_by_name['StartRequest'] = _STARTREQUEST
DESCRIPTOR.message_types_by_name['LockStatusRequest'] = _LOCKSTATUSREQUEST
DESCRIPTOR.message_types_by_name['LockStatusResponse'] = _LOCKSTATUSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StartRequest = _reflection.GeneratedProtocolMessageType('StartRequest', (_message.Message,), {
  'DESCRIPTOR' : _STARTREQUEST,
  '__module__' : 'application_pb2'
  # @@protoc_insertion_point(class_scope:PB_App.StartRequest)
  })
_sym_db.RegisterMessage(StartRequest)

LockStatusRequest = _reflection.GeneratedProtocolMessageType('LockStatusRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOCKSTATUSREQUEST,
  '__module__' : 'application_pb2'
  # @@protoc_insertion_point(class_scope:PB_App.LockStatusRequest)
  })
_sym_db.RegisterMessage(LockStatusRequest)

LockStatusResponse = _reflection.GeneratedProtocolMessageType('LockStatusResponse', (_message.Message,), {
  'DESCRIPTOR' : _LOCKSTATUSRESPONSE,
  '__module__' : 'application_pb2'
  # @@protoc_insertion_point(class_scope:PB_App.LockStatusResponse)
  })
_sym_db.RegisterMessage(LockStatusResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
