# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gui.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gui.proto',
  package='PB_Gui',
  syntax='proto3',
  serialized_options=b'\n\"com.flipperdevices.protobuf.screen',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tgui.proto\x12\x06PB_Gui\"\x1b\n\x0bScreenFrame\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x1a\n\x18StartScreenStreamRequest\"\x19\n\x17StopScreenStreamRequest\"W\n\x15SendInputEventRequest\x12\x1d\n\x03key\x18\x01 \x01(\x0e\x32\x10.PB_Gui.InputKey\x12\x1f\n\x04type\x18\x02 \x01(\x0e\x32\x11.PB_Gui.InputType\"F\n\x1aStartVirtualDisplayRequest\x12(\n\x0b\x66irst_frame\x18\x01 \x01(\x0b\x32\x13.PB_Gui.ScreenFrame\"\x1b\n\x19StopVirtualDisplayRequest*C\n\x08InputKey\x12\x06\n\x02UP\x10\x00\x12\x08\n\x04\x44OWN\x10\x01\x12\t\n\x05RIGHT\x10\x02\x12\x08\n\x04LEFT\x10\x03\x12\x06\n\x02OK\x10\x04\x12\x08\n\x04\x42\x41\x43K\x10\x05*D\n\tInputType\x12\t\n\x05PRESS\x10\x00\x12\x0b\n\x07RELEASE\x10\x01\x12\t\n\x05SHORT\x10\x02\x12\x08\n\x04LONG\x10\x03\x12\n\n\x06REPEAT\x10\x04\x42$\n\"com.flipperdevices.protobuf.screenb\x06proto3'
)

_INPUTKEY = _descriptor.EnumDescriptor(
  name='InputKey',
  full_name='PB_Gui.InputKey',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UP', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DOWN', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RIGHT', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LEFT', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OK', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BACK', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=295,
  serialized_end=362,
)
_sym_db.RegisterEnumDescriptor(_INPUTKEY)

InputKey = enum_type_wrapper.EnumTypeWrapper(_INPUTKEY)
_INPUTTYPE = _descriptor.EnumDescriptor(
  name='InputType',
  full_name='PB_Gui.InputType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PRESS', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RELEASE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SHORT', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LONG', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REPEAT', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=364,
  serialized_end=432,
)
_sym_db.RegisterEnumDescriptor(_INPUTTYPE)

InputType = enum_type_wrapper.EnumTypeWrapper(_INPUTTYPE)
UP = 0
DOWN = 1
RIGHT = 2
LEFT = 3
OK = 4
BACK = 5
PRESS = 0
RELEASE = 1
SHORT = 2
LONG = 3
REPEAT = 4



_SCREENFRAME = _descriptor.Descriptor(
  name='ScreenFrame',
  full_name='PB_Gui.ScreenFrame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='PB_Gui.ScreenFrame.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=48,
)


_STARTSCREENSTREAMREQUEST = _descriptor.Descriptor(
  name='StartScreenStreamRequest',
  full_name='PB_Gui.StartScreenStreamRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=76,
)


_STOPSCREENSTREAMREQUEST = _descriptor.Descriptor(
  name='StopScreenStreamRequest',
  full_name='PB_Gui.StopScreenStreamRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=103,
)


_SENDINPUTEVENTREQUEST = _descriptor.Descriptor(
  name='SendInputEventRequest',
  full_name='PB_Gui.SendInputEventRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='PB_Gui.SendInputEventRequest.key', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='PB_Gui.SendInputEventRequest.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=192,
)


_STARTVIRTUALDISPLAYREQUEST = _descriptor.Descriptor(
  name='StartVirtualDisplayRequest',
  full_name='PB_Gui.StartVirtualDisplayRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='first_frame', full_name='PB_Gui.StartVirtualDisplayRequest.first_frame', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=194,
  serialized_end=264,
)


_STOPVIRTUALDISPLAYREQUEST = _descriptor.Descriptor(
  name='StopVirtualDisplayRequest',
  full_name='PB_Gui.StopVirtualDisplayRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=266,
  serialized_end=293,
)

_SENDINPUTEVENTREQUEST.fields_by_name['key'].enum_type = _INPUTKEY
_SENDINPUTEVENTREQUEST.fields_by_name['type'].enum_type = _INPUTTYPE
_STARTVIRTUALDISPLAYREQUEST.fields_by_name['first_frame'].message_type = _SCREENFRAME
DESCRIPTOR.message_types_by_name['ScreenFrame'] = _SCREENFRAME
DESCRIPTOR.message_types_by_name['StartScreenStreamRequest'] = _STARTSCREENSTREAMREQUEST
DESCRIPTOR.message_types_by_name['StopScreenStreamRequest'] = _STOPSCREENSTREAMREQUEST
DESCRIPTOR.message_types_by_name['SendInputEventRequest'] = _SENDINPUTEVENTREQUEST
DESCRIPTOR.message_types_by_name['StartVirtualDisplayRequest'] = _STARTVIRTUALDISPLAYREQUEST
DESCRIPTOR.message_types_by_name['StopVirtualDisplayRequest'] = _STOPVIRTUALDISPLAYREQUEST
DESCRIPTOR.enum_types_by_name['InputKey'] = _INPUTKEY
DESCRIPTOR.enum_types_by_name['InputType'] = _INPUTTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ScreenFrame = _reflection.GeneratedProtocolMessageType('ScreenFrame', (_message.Message,), {
  'DESCRIPTOR' : _SCREENFRAME,
  '__module__' : 'gui_pb2'
  # @@protoc_insertion_point(class_scope:PB_Gui.ScreenFrame)
  })
_sym_db.RegisterMessage(ScreenFrame)

StartScreenStreamRequest = _reflection.GeneratedProtocolMessageType('StartScreenStreamRequest', (_message.Message,), {
  'DESCRIPTOR' : _STARTSCREENSTREAMREQUEST,
  '__module__' : 'gui_pb2'
  # @@protoc_insertion_point(class_scope:PB_Gui.StartScreenStreamRequest)
  })
_sym_db.RegisterMessage(StartScreenStreamRequest)

StopScreenStreamRequest = _reflection.GeneratedProtocolMessageType('StopScreenStreamRequest', (_message.Message,), {
  'DESCRIPTOR' : _STOPSCREENSTREAMREQUEST,
  '__module__' : 'gui_pb2'
  # @@protoc_insertion_point(class_scope:PB_Gui.StopScreenStreamRequest)
  })
_sym_db.RegisterMessage(StopScreenStreamRequest)

SendInputEventRequest = _reflection.GeneratedProtocolMessageType('SendInputEventRequest', (_message.Message,), {
  'DESCRIPTOR' : _SENDINPUTEVENTREQUEST,
  '__module__' : 'gui_pb2'
  # @@protoc_insertion_point(class_scope:PB_Gui.SendInputEventRequest)
  })
_sym_db.RegisterMessage(SendInputEventRequest)

StartVirtualDisplayRequest = _reflection.GeneratedProtocolMessageType('StartVirtualDisplayRequest', (_message.Message,), {
  'DESCRIPTOR' : _STARTVIRTUALDISPLAYREQUEST,
  '__module__' : 'gui_pb2'
  # @@protoc_insertion_point(class_scope:PB_Gui.StartVirtualDisplayRequest)
  })
_sym_db.RegisterMessage(StartVirtualDisplayRequest)

StopVirtualDisplayRequest = _reflection.GeneratedProtocolMessageType('StopVirtualDisplayRequest', (_message.Message,), {
  'DESCRIPTOR' : _STOPVIRTUALDISPLAYREQUEST,
  '__module__' : 'gui_pb2'
  # @@protoc_insertion_point(class_scope:PB_Gui.StopVirtualDisplayRequest)
  })
_sym_db.RegisterMessage(StopVirtualDisplayRequest)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
