# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: storage.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='storage.proto',
  package='PB_Storage',
  syntax='proto3',
  serialized_options=b'\n#com.flipperdevices.protobuf.storage',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rstorage.proto\x12\nPB_Storage\"x\n\x04\x46ile\x12\'\n\x04type\x18\x01 \x01(\x0e\x32\x19.PB_Storage.File.FileType\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04size\x18\x03 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c\"\x1d\n\x08\x46ileType\x12\x08\n\x04\x46ILE\x10\x00\x12\x07\n\x03\x44IR\x10\x01\"\x1b\n\x0bInfoRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\"7\n\x0cInfoResponse\x12\x13\n\x0btotal_space\x18\x01 \x01(\x04\x12\x12\n\nfree_space\x18\x02 \x01(\x04\"\x1b\n\x0bStatRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\".\n\x0cStatResponse\x12\x1e\n\x04\x66ile\x18\x01 \x01(\x0b\x32\x10.PB_Storage.File\"\x1b\n\x0bListRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\".\n\x0cListResponse\x12\x1e\n\x04\x66ile\x18\x01 \x03(\x0b\x32\x10.PB_Storage.File\"\x1b\n\x0bReadRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\".\n\x0cReadResponse\x12\x1e\n\x04\x66ile\x18\x01 \x01(\x0b\x32\x10.PB_Storage.File\"<\n\x0cWriteRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x1e\n\x04\x66ile\x18\x02 \x01(\x0b\x32\x10.PB_Storage.File\"0\n\rDeleteRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x11\n\trecursive\x18\x02 \x01(\x08\"\x1c\n\x0cMkdirRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\"\x1d\n\rMd5sumRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\" \n\x0eMd5sumResponse\x12\x0e\n\x06md5sum\x18\x01 \x01(\t\"3\n\rRenameRequest\x12\x10\n\x08old_path\x18\x01 \x01(\t\x12\x10\n\x08new_path\x18\x02 \x01(\t\"+\n\x13\x42\x61\x63kupCreateRequest\x12\x14\n\x0c\x61rchive_path\x18\x01 \x01(\t\",\n\x14\x42\x61\x63kupRestoreRequest\x12\x14\n\x0c\x61rchive_path\x18\x01 \x01(\tB%\n#com.flipperdevices.protobuf.storageb\x06proto3'
)



_FILE_FILETYPE = _descriptor.EnumDescriptor(
  name='FileType',
  full_name='PB_Storage.File.FileType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FILE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DIR', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=120,
  serialized_end=149,
)
_sym_db.RegisterEnumDescriptor(_FILE_FILETYPE)


_FILE = _descriptor.Descriptor(
  name='File',
  full_name='PB_Storage.File',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='PB_Storage.File.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='PB_Storage.File.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='size', full_name='PB_Storage.File.size', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='PB_Storage.File.data', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _FILE_FILETYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=149,
)


_INFOREQUEST = _descriptor.Descriptor(
  name='InfoRequest',
  full_name='PB_Storage.InfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='PB_Storage.InfoRequest.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=178,
)


_INFORESPONSE = _descriptor.Descriptor(
  name='InfoResponse',
  full_name='PB_Storage.InfoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='total_space', full_name='PB_Storage.InfoResponse.total_space', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='free_space', full_name='PB_Storage.InfoResponse.free_space', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=180,
  serialized_end=235,
)


_STATREQUEST = _descriptor.Descriptor(
  name='StatRequest',
  full_name='PB_Storage.StatRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='PB_Storage.StatRequest.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=237,
  serialized_end=264,
)


_STATRESPONSE = _descriptor.Descriptor(
  name='StatResponse',
  full_name='PB_Storage.StatResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='file', full_name='PB_Storage.StatResponse.file', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=266,
  serialized_end=312,
)


_LISTREQUEST = _descriptor.Descriptor(
  name='ListRequest',
  full_name='PB_Storage.ListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='PB_Storage.ListRequest.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=314,
  serialized_end=341,
)


_LISTRESPONSE = _descriptor.Descriptor(
  name='ListResponse',
  full_name='PB_Storage.ListResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='file', full_name='PB_Storage.ListResponse.file', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=343,
  serialized_end=389,
)


_READREQUEST = _descriptor.Descriptor(
  name='ReadRequest',
  full_name='PB_Storage.ReadRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='PB_Storage.ReadRequest.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=391,
  serialized_end=418,
)


_READRESPONSE = _descriptor.Descriptor(
  name='ReadResponse',
  full_name='PB_Storage.ReadResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='file', full_name='PB_Storage.ReadResponse.file', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=420,
  serialized_end=466,
)


_WRITEREQUEST = _descriptor.Descriptor(
  name='WriteRequest',
  full_name='PB_Storage.WriteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='PB_Storage.WriteRequest.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='file', full_name='PB_Storage.WriteRequest.file', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=468,
  serialized_end=528,
)


_DELETEREQUEST = _descriptor.Descriptor(
  name='DeleteRequest',
  full_name='PB_Storage.DeleteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='PB_Storage.DeleteRequest.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='recursive', full_name='PB_Storage.DeleteRequest.recursive', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=530,
  serialized_end=578,
)


_MKDIRREQUEST = _descriptor.Descriptor(
  name='MkdirRequest',
  full_name='PB_Storage.MkdirRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='PB_Storage.MkdirRequest.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=580,
  serialized_end=608,
)


_MD5SUMREQUEST = _descriptor.Descriptor(
  name='Md5sumRequest',
  full_name='PB_Storage.Md5sumRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='PB_Storage.Md5sumRequest.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=610,
  serialized_end=639,
)


_MD5SUMRESPONSE = _descriptor.Descriptor(
  name='Md5sumResponse',
  full_name='PB_Storage.Md5sumResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='md5sum', full_name='PB_Storage.Md5sumResponse.md5sum', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=641,
  serialized_end=673,
)


_RENAMEREQUEST = _descriptor.Descriptor(
  name='RenameRequest',
  full_name='PB_Storage.RenameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='old_path', full_name='PB_Storage.RenameRequest.old_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='new_path', full_name='PB_Storage.RenameRequest.new_path', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=675,
  serialized_end=726,
)


_BACKUPCREATEREQUEST = _descriptor.Descriptor(
  name='BackupCreateRequest',
  full_name='PB_Storage.BackupCreateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='archive_path', full_name='PB_Storage.BackupCreateRequest.archive_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=728,
  serialized_end=771,
)


_BACKUPRESTOREREQUEST = _descriptor.Descriptor(
  name='BackupRestoreRequest',
  full_name='PB_Storage.BackupRestoreRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='archive_path', full_name='PB_Storage.BackupRestoreRequest.archive_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=773,
  serialized_end=817,
)

_FILE.fields_by_name['type'].enum_type = _FILE_FILETYPE
_FILE_FILETYPE.containing_type = _FILE
_STATRESPONSE.fields_by_name['file'].message_type = _FILE
_LISTRESPONSE.fields_by_name['file'].message_type = _FILE
_READRESPONSE.fields_by_name['file'].message_type = _FILE
_WRITEREQUEST.fields_by_name['file'].message_type = _FILE
DESCRIPTOR.message_types_by_name['File'] = _FILE
DESCRIPTOR.message_types_by_name['InfoRequest'] = _INFOREQUEST
DESCRIPTOR.message_types_by_name['InfoResponse'] = _INFORESPONSE
DESCRIPTOR.message_types_by_name['StatRequest'] = _STATREQUEST
DESCRIPTOR.message_types_by_name['StatResponse'] = _STATRESPONSE
DESCRIPTOR.message_types_by_name['ListRequest'] = _LISTREQUEST
DESCRIPTOR.message_types_by_name['ListResponse'] = _LISTRESPONSE
DESCRIPTOR.message_types_by_name['ReadRequest'] = _READREQUEST
DESCRIPTOR.message_types_by_name['ReadResponse'] = _READRESPONSE
DESCRIPTOR.message_types_by_name['WriteRequest'] = _WRITEREQUEST
DESCRIPTOR.message_types_by_name['DeleteRequest'] = _DELETEREQUEST
DESCRIPTOR.message_types_by_name['MkdirRequest'] = _MKDIRREQUEST
DESCRIPTOR.message_types_by_name['Md5sumRequest'] = _MD5SUMREQUEST
DESCRIPTOR.message_types_by_name['Md5sumResponse'] = _MD5SUMRESPONSE
DESCRIPTOR.message_types_by_name['RenameRequest'] = _RENAMEREQUEST
DESCRIPTOR.message_types_by_name['BackupCreateRequest'] = _BACKUPCREATEREQUEST
DESCRIPTOR.message_types_by_name['BackupRestoreRequest'] = _BACKUPRESTOREREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

File = _reflection.GeneratedProtocolMessageType('File', (_message.Message,), {
  'DESCRIPTOR' : _FILE,
  '__module__' : 'storage_pb2'
  # @@protoc_insertion_point(class_scope:PB_Storage.File)
  })
_sym_db.RegisterMessage(File)

InfoRequest = _reflection.GeneratedProtocolMessageType('InfoRequest', (_message.Message,), {
  'DESCRIPTOR' : _INFOREQUEST,
  '__module__' : 'storage_pb2'
  # @@protoc_insertion_point(class_scope:PB_Storage.InfoRequest)
  })
_sym_db.RegisterMessage(InfoRequest)

InfoResponse = _reflection.GeneratedProtocolMessageType('InfoResponse', (_message.Message,), {
  'DESCRIPTOR' : _INFORESPONSE,
  '__module__' : 'storage_pb2'
  # @@protoc_insertion_point(class_scope:PB_Storage.InfoResponse)
  })
_sym_db.RegisterMessage(InfoResponse)

StatRequest = _reflection.GeneratedProtocolMessageType('StatRequest', (_message.Message,), {
  'DESCRIPTOR' : _STATREQUEST,
  '__module__' : 'storage_pb2'
  # @@protoc_insertion_point(class_scope:PB_Storage.StatRequest)
  })
_sym_db.RegisterMessage(StatRequest)

StatResponse = _reflection.GeneratedProtocolMessageType('StatResponse', (_message.Message,), {
  'DESCRIPTOR' : _STATRESPONSE,
  '__module__' : 'storage_pb2'
  # @@protoc_insertion_point(class_scope:PB_Storage.StatResponse)
  })
_sym_db.RegisterMessage(StatResponse)

ListRequest = _reflection.GeneratedProtocolMessageType('ListRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTREQUEST,
  '__module__' : 'storage_pb2'
  # @@protoc_insertion_point(class_scope:PB_Storage.ListRequest)
  })
_sym_db.RegisterMessage(ListRequest)

ListResponse = _reflection.GeneratedProtocolMessageType('ListResponse', (_message.Message,), {
  'DESCRIPTOR' : _LISTRESPONSE,
  '__module__' : 'storage_pb2'
  # @@protoc_insertion_point(class_scope:PB_Storage.ListResponse)
  })
_sym_db.RegisterMessage(ListResponse)

ReadRequest = _reflection.GeneratedProtocolMessageType('ReadRequest', (_message.Message,), {
  'DESCRIPTOR' : _READREQUEST,
  '__module__' : 'storage_pb2'
  # @@protoc_insertion_point(class_scope:PB_Storage.ReadRequest)
  })
_sym_db.RegisterMessage(ReadRequest)

ReadResponse = _reflection.GeneratedProtocolMessageType('ReadResponse', (_message.Message,), {
  'DESCRIPTOR' : _READRESPONSE,
  '__module__' : 'storage_pb2'
  # @@protoc_insertion_point(class_scope:PB_Storage.ReadResponse)
  })
_sym_db.RegisterMessage(ReadResponse)

WriteRequest = _reflection.GeneratedProtocolMessageType('WriteRequest', (_message.Message,), {
  'DESCRIPTOR' : _WRITEREQUEST,
  '__module__' : 'storage_pb2'
  # @@protoc_insertion_point(class_scope:PB_Storage.WriteRequest)
  })
_sym_db.RegisterMessage(WriteRequest)

DeleteRequest = _reflection.GeneratedProtocolMessageType('DeleteRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETEREQUEST,
  '__module__' : 'storage_pb2'
  # @@protoc_insertion_point(class_scope:PB_Storage.DeleteRequest)
  })
_sym_db.RegisterMessage(DeleteRequest)

MkdirRequest = _reflection.GeneratedProtocolMessageType('MkdirRequest', (_message.Message,), {
  'DESCRIPTOR' : _MKDIRREQUEST,
  '__module__' : 'storage_pb2'
  # @@protoc_insertion_point(class_scope:PB_Storage.MkdirRequest)
  })
_sym_db.RegisterMessage(MkdirRequest)

Md5sumRequest = _reflection.GeneratedProtocolMessageType('Md5sumRequest', (_message.Message,), {
  'DESCRIPTOR' : _MD5SUMREQUEST,
  '__module__' : 'storage_pb2'
  # @@protoc_insertion_point(class_scope:PB_Storage.Md5sumRequest)
  })
_sym_db.RegisterMessage(Md5sumRequest)

Md5sumResponse = _reflection.GeneratedProtocolMessageType('Md5sumResponse', (_message.Message,), {
  'DESCRIPTOR' : _MD5SUMRESPONSE,
  '__module__' : 'storage_pb2'
  # @@protoc_insertion_point(class_scope:PB_Storage.Md5sumResponse)
  })
_sym_db.RegisterMessage(Md5sumResponse)

RenameRequest = _reflection.GeneratedProtocolMessageType('RenameRequest', (_message.Message,), {
  'DESCRIPTOR' : _RENAMEREQUEST,
  '__module__' : 'storage_pb2'
  # @@protoc_insertion_point(class_scope:PB_Storage.RenameRequest)
  })
_sym_db.RegisterMessage(RenameRequest)

BackupCreateRequest = _reflection.GeneratedProtocolMessageType('BackupCreateRequest', (_message.Message,), {
  'DESCRIPTOR' : _BACKUPCREATEREQUEST,
  '__module__' : 'storage_pb2'
  # @@protoc_insertion_point(class_scope:PB_Storage.BackupCreateRequest)
  })
_sym_db.RegisterMessage(BackupCreateRequest)

BackupRestoreRequest = _reflection.GeneratedProtocolMessageType('BackupRestoreRequest', (_message.Message,), {
  'DESCRIPTOR' : _BACKUPRESTOREREQUEST,
  '__module__' : 'storage_pb2'
  # @@protoc_insertion_point(class_scope:PB_Storage.BackupRestoreRequest)
  })
_sym_db.RegisterMessage(BackupRestoreRequest)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
